### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by gbryer** [ljbc1994/BlazorIntersectionObserver#35] opened 2021-10-06 14:36 UTC
When publishing my project the blazor-intersection-observer.min.js fails to load. 

```crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: https://*.com/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js
      TypeError: Failed to fetch dynamically imported module: https://*.com/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://*.com/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js
TypeError: Failed to fetch dynamically imported module: https://*.com/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Ljbc1994.Blazor.IntersectionObserver.IntersectionObserverService.Observe(ElementReference element, Action`1 onIntersectUpdate, IntersectionObserverOptions options)
   at *.Frontend.Shared.MainLayout.SetupObservers()
   at *.Frontend.Shared.MainLayout.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```
   
   
At a glance it could be that instead of ``/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js`` it should be ``./_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js`` at https://github.com/ljbc1994/BlazorIntersectionObserver/blob/bc7532696b93252a8dad622fcdaefa272b9221e0/src/Ljbc1994.Blazor.IntersectionObserver/IntersectionObserverService.cs#L14

**Comment by epicturkey** [comment] 2021-10-13 21:59
I have the same issue - it is caused by having the Blazor app running in a subfolder of the root directory.
Ie in **debug** our Base Url is the root of the domain, ie **www.myDomain.com**
In **release**, we have put it at **www.myDomain.com/pages/myBlazorApp**
ie, in Startup:
`app.UsePathBase("pages/myBlazorApp");`
and in _Layout, we add:
```
<head>
    <base href="~/" />
```
But this nuget does not appear to be obeying our baseurl, and is still looking for the .js file in the _content folder at the root of the website, ie:
www.myDomain.com/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js
instead of
www.myDomain.com/pages/myBlazorApp/_content/BlazorIntersectionObserver/blazor-intersection-observer.min.js

I suggest the author use the NavigationManager service injection to resolve the problem and format the URL from the `navigationManager.BaseUrl `property, or using `NavigationManagerInstance.ToAbsoluteUri(string relative)`

I just now figured this all out. As a temporary workaround, you can copy the _content folder to the root of your website, which solves the problem.

I do hope this gets fixed soon - thanks for your hard work ljbc1994!

**Comment by epicturkey** [comment] 2021-10-14 14:12
@gbryer I have contributed a pull request with a fix for this issue, please see
https://github.com/ljbc1994/BlazorIntersectionObserver/pull/36

**Closed as completed** 2021-10-15 20:46 UTC
